insert into role(name) values ('Managers');
insert into role(name) values ('Analysts');
insert into role(name) values ('Support');
insert into rules(name) values ('Read');
insert into rules(name) values ('Write');
insert into rules(name) values ('Admin');
insert into role_rules(role_id, rules_id) values (1, 1);
insert into role_rules(role_id, rules_id) values (1, 2);
insert into role_rules(role_id, rules_id) values (2, 1);
insert into role_rules(role_id, rules_id) values (3, 3);
insert into users(user_name, pass, role_id) values ('Ivan', 'password', 1);
insert into users(user_name, pass, role_id) values ('Bob', 'passw0rd', 3);
insert into users(user_name, pass, role_id) values ('Alex', 'password123', 2);
insert into category(name, score) values ('Important', 1000);
insert into category(name, score) values ('Simple', 500);
insert into state(name) values ('new');
insert into state(name) values ('progress');
insert into state(name) values ('done');
insert into item(short_description, users_id, category_id, state_id) VALUES ('Install a printer...', 1, 2, 1);
insert into item(short_description, users_id, category_id, state_id) VALUES ('Debug the programm', 3, 2, 1);
insert into comments(description, item_id) VALUES ('cab.#58', 1);
insert into comments(description, item_id) VALUES ('We need this printer...', 1);
insert into comments(description, item_id) VALUES ('Peter is the responsible person', 2);
insert into attachs(description, item_id, link_file_att) VALUES ('Bug#1', 2, './prnScrn/1.jpg');
insert into attachs(description, item_id, link_file_att) VALUES ('Bug#2', 2, './prnScrn/2.jpg');